[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'let g:deoplete#enable_at_startup = 1'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
let g:quickrun_config = {
\   "_" : {
\       "runner" : "vimproc",
\       "outputter/" : "error",
\       "outputter/buffer/split" : ":rightbelow 8sp",
\       "outputter/error/sucess" : "buffer",
\       "outputter/error/error"  : "quickfix",
\       "outputter/buffer/close_on_empty" : 1,
\   }
\}
'''

# color setting
[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo =  'koalaman/shellcheck'

[[plugins]]
repo = 'vim-syntastic/syntastic'
hook_add = 'let g:syntastic_mode_map = { "mode": "passive",
    \ "active_filetypes": ["go"] }'
hook_add = 'let g:syntastic_go_checkers = ["go", "golint"]'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'jcf/vim-latex'

[[plugins]]
repo = 'justmao945/vim-clang'
hook_add = 'let g:clang_c_options = "-std=c11"'
hook_add = 'let g:clang_cpp_options = "-std=c++1z -stdlib=libc++ --pedantic-errors"'

[[plugins]]
repo = 'Yggdroot/indentLine'

# for go lang.
[[plugins]]
repo = 'zchee/deoplete-go'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'golang/lint'

[[plugins]]
repo = 'jiangmiao/auto-pairs'
hook_add = 'let g:AutoPairsFlyMode = 1'
