[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'let g:deoplete#enable_at_startup = 1'

# color setting
[[plugins]]
repo = 'nanotech/jellybeans.vim'
#repo = 'w0ng/vim-hybrid'
#repo = 'jacoborus/tender.vim'
#repo = 'cocopon/iceberg.vim'

[[plugins]]
repo =  'koalaman/shellcheck'

[[plugins]]
repo = 'vim-syntastic/syntastic'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'jcf/vim-latex'

[[plugins]]
repo = 'justmao945/vim-clang'
hook_source = 'let g:clang_c_options = "-std=c11"'
hook_source = 'let g:clang_cpp_options = "-std=c++1z -stdlib=libc++ --pedantic-errors"'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'zchee/deoplete-go'
