[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'let g:deoplete#enable_at_startup = 1'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'zchee/deoplete-jedi'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
let g:quickrun_config = {
\   "_" : {
\       "runner" : "vimproc",
\       "outputter/" : "error",
\       "outputter/buffer/split" : ":rightbelow 8sp",
\       "outputter/error/sucess" : "buffer",
\       "outputter/error/error"  : "quickfix",
\       "outputter/buffer/close_on_empty" : 1,
\   }
\}
'''

# color setting
[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo =  'koalaman/shellcheck'

[[plugins]]
repo = 'vim-syntastic/syntastic'
hook_add = 'let g:syntastic_mode_map = { "mode": "passive",
    \ "active_filetypes": ["go"] }'
hook_add = 'let g:syntastic_go_checkers = ["go", "golint"]'
hook_add = 'let g:syntastic_python_checkers = ["pycodestyle"]'
hook_add = 'let g:pep8_ignore="E501,E402"'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'jcf/vim-latex'

[[plugins]]
repo = 'justmao945/vim-clang'
hook_add = 'let g:clang_c_options = "-std=c11"'
hook_add = 'let g:clang_cpp_options = "-std=c++1z -stdlib=libc++ --pedantic-errors"'

[[plugins]]
repo = 'Yggdroot/indentLine'

# for go lang.
[[plugins]]
repo = 'zchee/deoplete-go'

[[plugins]]
repo = 'fatih/vim-go'
depends = 'SirVer/ultisnips'
hook_add = 'let g:UltiSnipsExpandTrigger = "<tab>"'
hook_add = 'let g:UltiSnipsJumpForwardTrigger = "<tab>"'
hook_add = 'let g:UltiSnipsJumpBackwardTrigger = "<s-tab>"'
hook_add = 'let g:go_fmt_command = "goimports"'

[[plugins]]
repo = 'SirVer/ultisnips'

[[plugins]]
repo = 'golang/lint'

[[plugins]]
repo = 'jiangmiao/auto-pairs'
#hook_add = 'let g:AutoPairsFlyMode = 1'
#hook_add = 'let g:AutoPairsShortcutBackInsert = "<C-i>"'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'

[[plugins]]
repo = 'tell-k/vim-autopep8'

[[plugins]]
repo = 'nvie/vim-flake8'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'sebdah/vim-delve'

[[plugins]]
repo = 'posva/vim-vue'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = ''

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'

[[plugins]]
repo = 'majutsushi/tagbar'
depends = 'ctags'
hook_add = 'let g:tagbar_autofocus = 1'
hook_add = 'let g:tagbar_autoclose = 1'

[[plugins]]
repo = "airblade/vim-gitgutter"

[[plugins]]
repo = "tpope/vim-fugitive"

[[plugins]]
repo = "autowitch/hive.vim"

[[plugins]]
repo = "hashivim/vim-terraform"

[[plugins]]
repo = "tsandall/vim-rego"
